---

services:
  jekyll-container:
    build: . 
    container_name: dev_jekyll
    restart: always
    tty: true
    volumes:
      - ./app:/app
      - ./dev-configs:/etc/nginx/conf.d
    ports:
      - target: 4000
        published: 80
    networks:
    - jekyll-network
    command: bundle exec jekyll serve --livereload --host 0.0.0.0

  
networks:
  jekyll-network:
    driver: bridge