
source 'https://rubygems.org'

gem 'jekyll', "3.10.0"

gem 'bundler'

gem 'rouge', " 3.30.0"
gem 'webrick', '~> 1.8', '>=1.8.2'
###gem 'sass-embedded', '~> 1.80', '>= 1.80.4'
gem 'kramdown-parser-gfm', "1.1.0" 

group :jekyll_plugins do
    gem 'jekyll-paginate', "1.1.0"
    gem 'jekyll-sitemap', "1.4.0"
  end